### ISSUE TITLE
ember 3 compatibility

### ISSUE THREAD

**Issue by basz** [mirego/ember-best-language#14]
Hi, I just upgrade my app from 2.18.4 to 3.0.4 and are getting error on this addon;

From the console;

```
console-consumer.js:11 window Error: Assertion Failed: You attempted to access `fastboot.isFastBoot` (on `<Ember.Service:ember28>`), but `fastboot` is a computed property.:Assertion Failed: You attempted to access `fastboot.isFastBoot` (on `<Ember.Service:ember28>`), but `fastboot` is a computed property.

Due to certain internal implementation details of Ember, the `fastboot` property previously contained a private "descriptor" object, therefore `fastboot.isFastBoot` would have been `undefined`.

This implementation detail has now changed and the "descriptor" object is no longer present at this location. Soon, accessing `fastboot` on this object will return the computed property's current value (see RFC #281 for more details).

If you are seeing this error, you are likely using an addon that relies on this now-defunct private implementation detail. If you can, identify the addon from the stack trace below and report this bug to the addon authors. If you feel stuck, the Ember Community Slack (https://ember-community-slackin.herokuapp.com/) may be able to offer some help.

If you are an addon author and need help transitioning your code, please get in touch in the #dev-ember channel in the Ember Community Slack.

Due to certain internal implementation details of Ember, the `fastboot` property previously contained a private "descriptor" object, therefore `fastboot.isFastBoot` would have been `undefined`.

This implementation detail has now changed and the "descriptor" object is no longer present at this location. Soon, accessing `fastboot` on this object will return the computed property's current value (see RFC #281 for more details).

If you are seeing this error, you are likely using an addon that relies on this now-defunct private implementation detail. If you can, identify the addon from the stack trace below and report this bug to the addon authors. If you feel stuck, the Ember Community Slack (https://ember-community-slackin.herokuapp.com/) may be able to offer some help.

If you are an addon author and need help transitioning your code, please get in touch in the #dev-ember channel in the Ember Community Slack.
    at new EmberError (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:28721:25)
    at Object.assert (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:28964:15)
    at Object.get (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:38404:42)
    at BestLanguage.bestLanguage (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:101861:60)
    at BestLanguage.bestLanguageOrFirst (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:101868:33)
    at Class.<anonymous> (https://localhost:4201/assets/plhw-client-468fbff1eedeb089d410147a0a1aceb0.js:23166:39)
    at ComputedPropertyPrototype.get (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:40588:28)
    at get (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:39959:27)
    at Class.get (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:52872:34)
    at Object.initialize (https://localhost:4201/assets/plhw-client-468fbff1eedeb089d410147a0a1aceb0.js:7028:74)
    at https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:27719:21
    at Vertices.each (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:26386:17)
    at Vertices.walk (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:26315:18)
    at DAG.each (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:26260:28)
    at DAG.topsort (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:26266:18)
    at Class._runInitializer (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:27733:13)
    at Class.runInstanceInitializers (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:27716:12)
    at Class._bootSync (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:26563:24)
    at Class.didBecomeReady (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:27318:20)
    at invoke (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:24589:24)
    at Queue.flush (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:24509:25)
    at DeferredActionQueues.flush (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:24662:31)
    at Backburner.end (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:24794:42)
    at Backburner._run (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:25144:26)
    at Backburner._join (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:25120:29)
    at Backburner.join (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:24861:25)
    at Function.run.join (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:41564:30)
    at HTMLDocument.<anonymous> (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:41639:23)
    at mightThrow (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:8469:29)
    at process (https://localhost:4201/assets/vendor-68effba927d4ce1bd6edb6a52068e536.js:8537:12)
```

Not sure what I can do about this. We are not using fast boot.

**Comment by charlesdemers** [comment]
I think the problem comes from the fact that we use ES5 getters which were introduced in Ember 3.1. Do you plan on updating your app to > 3.1?

**Comment by basz** [comment]
That is the plan Yes.

You think it might work with 3.1+?

**Comment by charlesdemers** [comment]
I think so yes! Please report back if this doesn’t work on 3.1. Currently we test for 3.4+, maybe we can add support for older versions if it helps!

**Comment by basz** [comment]
confirmed to work again on 3.1! thanks! on to 3.2...
